# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

#Order Value Analysis and Outlier Detection
"""

orders = [1200, 3400, 560, 8900, 2300, 1200, 3400]

orders_set=set(orders)
orders_set

unique_orders = list(orders_set)
unique_orders

unique_orders.sort()
print("Unique sorted orders:", unique_orders)

top_3_orders = unique_orders[-3:]
print("Top 3 highest orders:", top_3_orders)

def detect_outliers(values):
    sorted_values = sorted(values)

    q1 = sorted_values[int(0.25 * (len(sorted_values) - 1))]
    q3 = sorted_values[int(0.75 * (len(sorted_values) - 1))]

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = []
    for x in values:
        if x < lower or x > upper:
            outliers.append(x)

    return outliers

outliers = detect_outliers(orders)
print("Outliers:", outliers)

import matplotlib.pyplot as plt

plt.plot(orders, marker='o', label="Orders")

# highlight outliers
for i, value in enumerate(orders):
    if value in outliers:
        plt.scatter(i, value, color='red')
        plt.text(i, value, " Outlier", color='red')

plt.title("Order Trend with Outliers")
plt.xlabel("Index")
plt.ylabel("Order Value")

plt.legend()
plt.show()