# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Random Dataset Generation for E-Commerce Orders, Customers, Products, and Order Items

####This notebook generates a random e-commerce dataset using Python.
####Each time the code is run, a different dataset is created.
####my dataset has already been downloaded and saved,
####so the same dataset is available for review without re-running this notebook.
"""

pip install faker pandas

from faker import Faker
import random
import pandas as pd

fake = Faker()

# ----------------- Customers -----------------
cities = ["New York","Los Angeles","Chicago","Houston","Phoenix",
          "Philadelphia","San Antonio","San Diego","Dallas","San Jose"]

num_customers = 500
customers = []

for i in range(1, num_customers + 1):
    customers.append([
        i,
        fake.name(),
        random.choice(cities),
        fake.date_between(start_date='-3y', end_date='today')  # datetime object
    ])

customers_df = pd.DataFrame(customers, columns=["CustomerID","CustomerName","City","SignUpDate"])

# Convert SignUpDate to string YYYY-MM-DD for SQL Server
customers_df['SignUpDate'] = pd.to_datetime(customers_df['SignUpDate'], errors='coerce').dt.strftime('%Y-%m-%d')

customers_df.to_csv("customers.csv", index=False)
print("customers.csv created!")

# ----------------- Products -----------------
product_list = [
    ("Laptop", "Electronics"),
    ("Smartphone", "Electronics"),
    ("Headphones", "Electronics"),
    ("T-Shirt", "Fashion"),
    ("Jeans", "Fashion"),
    ("Jacket", "Fashion"),
    ("Sofa", "Home"),
    ("Coffee Table", "Home"),
    ("Lamp", "Home"),
    ("Lipstick", "Beauty"),
    ("Perfume", "Beauty"),
    ("Book", "Books"),
]

products = []
product_id = 1
for prod, cat in product_list:
    price = round(random.uniform(10, 500), 2)  # fixed price
    products.append([product_id, prod, cat, price])
    product_id += 1

# Add 2 extra products never ordered
extra_products = [
    ("Board Game", "Toys"),
    ("Desk Organizer", "Office")
]
for prod, cat in extra_products:
    price = round(random.uniform(10, 500), 2)
    products.append([product_id, prod, cat, price])
    product_id += 1

products_df = pd.DataFrame(products, columns=["ProductID","ProductName","Category","UnitPrice"])
products_df.to_csv("products.csv", index=False)
print("products.csv created!")

# ----------------- Product price map -----------------
price_map = {p[0]: p[3] for p in products}  # ProductID -> UnitPrice

# ----------------- Orders and Order Items -----------------
num_orders = 2000
orders = []
order_items = []
order_item_id = 1

for order_id in range(1, num_orders + 1):
    # Pick a random customer
    customer = random.choice(customers)
    customer_id = customer[0]
    signup_date = customer[3]  # string format now

    # Order date after signup
    order_date = fake.date_between(start_date=signup_date, end_date='today')

    # Number of different products in this order
    num_items = random.randint(1, 5)

    # Randomly pick products for this order (no duplicates)
    product_ids = random.sample(range(1, 13), k=num_items)  # only first 12 products can be ordered

    for pid in product_ids:
        quantity = random.randint(1, 3)
        unit_price = price_map[pid]
        line_total = round(unit_price * quantity, 2)

        order_items.append([
            order_item_id,
            order_id,
            pid,
            quantity,
            line_total
        ])
        order_item_id += 1

    orders.append([order_id, customer_id, order_date, 0])  # placeholder for total

# Convert to DataFrames
orders_df = pd.DataFrame(orders, columns=["OrderID","CustomerID","OrderDate","OrderValue"])

# Convert OrderDate to string YYYY-MM-DD for SQL Server
orders_df['OrderDate'] = pd.to_datetime(orders_df['OrderDate'], errors='coerce').dt.strftime('%Y-%m-%d')

order_items_df = pd.DataFrame(order_items, columns=["OrderItemID","OrderID","ProductID","Quantity","Price"])

# Calculate order totals correctly
orders_df['OrderValue'] = order_items_df.groupby('OrderID')['Price'].sum().values

# Save CSVs
orders_df.to_csv("orders.csv", index=False)
order_items_df.to_csv("order_items.csv", index=False)
print("orders.csv and order_items.csv created!")
print("All CSV files ready! ")

