# -*- coding: utf-8 -*-
"""MarketBasketAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYLZ_KDITULWwATEWf_S853zolbRDgYZ

# Product Bundling Recommendations Using Market Basket Analysis (Apriori Algorithm)
"""

from google.colab import files
uploaded = files.upload()
# i uploaded the data set i created

import warnings
warnings.filterwarnings('ignore')
# i Ignored the DeprecationWarnings from Jupyter/Colab.
# These warnings come from the environment and do not affect the results of this analysis.
# to keep the notebook clean so the focus is on the data and insights.

import pandas as pd

customers = pd.read_csv('customers (1).csv')
orders = pd.read_csv('orders.csv')
order_items = pd.read_csv('order_items.csv')
products = pd.read_csv('products.csv')

df = order_items.merge(orders, on='OrderID') \
                .merge(products, on='ProductID') \
                .merge(customers, on='CustomerID')

df.head()

#merging all the tables so i can analyse all the dataset at once.

basket = df.groupby(['OrderID', 'ProductName'])['Quantity'] \
           .sum().unstack().fillna(0)

# Convert to binary so it became easy to read and know which product is ordered.
basket = basket.applymap(lambda x: 1 if x > 0 else 0)

basket.head()

!pip install mlxtend
#machine learning library so i can use the apriori algorithm

from mlxtend.frequent_patterns import apriori, association_rules

# Find frequent itemsets
frequent_items = apriori(basket, min_support=0.02, use_colnames=True)

# Generate rules
rules = association_rules(frequent_items, metric="lift", min_threshold=1)

rules.head()

# Filter pairs only
rules['length'] = rules['antecedents'].apply(lambda x: len(x)) + \
                  rules['consequents'].apply(lambda x: len(x))

pairs = rules[rules['length'] == 2]

# Sort by lift (strongest relationship)
top_pairs = pairs.sort_values(by='lift', ascending=False)

top_pairs[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

def recommend(product_name):
    recommendations = rules[rules['antecedents'].apply(lambda x: product_name in x)]
    return recommendations.sort_values(by='confidence', ascending=False)[
        ['antecedents', 'consequents', 'confidence']
    ].head(5)

recommend('Lipstick')  # we can change the product name for another recommendations

import matplotlib.pyplot as plt
import numpy as np

# Prepare labels like "Smartphone → Sofa"
labels = top_pairs.head(5).apply(
    lambda row: f"{list(row['antecedents'])[0]} → {list(row['consequents'])[0]}",
    axis=1
)

lift_values = top_pairs.head(5)['lift']

plt.figure(figsize=(10,6))

# Bar plot
bars = plt.bar(labels, lift_values, color='skyblue', edgecolor='black')

# Add grid lines so we know the number
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Y-axis: create finer ticks (small intervals)
y_min = lift_values.min() - 0.01
y_max = lift_values.max() + 0.01
plt.ylim(y_min, y_max)
plt.yticks(np.round(np.linspace(y_min, y_max, 10), 3))  # 10 ticks

# Add bar labels on top
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.005, f'{height:.3f}',
             ha='center', va='bottom', fontsize=10)

# Titles and labels
plt.title('Top Product Pairs by Lift', fontsize=14)
plt.ylabel('Lift', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()